# C++ standard
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

include(CheckCXXCompilerFlag)
function(enable_cxx_compiler_flag_if_supported flag)
    string(FIND "${CMAKE_CXX_FLAGS}" "${flag}" flag_already_set)
    if(flag_already_set EQUAL -1)
        check_cxx_compiler_flag("${flag}" flag_supported)
        if(flag_supported)
            add_compile_options(${flag})
        elseif(flag_supported)
            message(WARNING "unsupported compiler flag: ${flag}")
        endif(flag_supported)
        unset(flag_supported CACHE)
    endif()
endfunction()

# Compiler warning options
option(ENABLE_PEDANTIC "Enable pedantic compile mode" ON)
option(ENABLE_STRICT "Enable strict compile mode" ON)
option(ENABLE_WERROR "Enable treating warning as error" ON)

# Debug options
option (ENABLE_ADDRESS_SANITIZER "enable address sanitizer support" OFF)
option (ENABLE_UB_SANITIZER "enable undefined behavior sanitizer support" OFF)
option (ENABLE_THREAD_SANITIZER "enable thread sanitizer support" OFF)

if (ENABLE_PEDANTIC)
    enable_cxx_compiler_flag_if_supported(-Wpedantic)
endif (ENABLE_PEDANTIC)

if (ENABLE_STRICT)
    enable_cxx_compiler_flag_if_supported(-Wall)
    enable_cxx_compiler_flag_if_supported(-Wextra)
endif (ENABLE_STRICT)

if (ENABLE_WERROR)
    enable_cxx_compiler_flag_if_supported(-Werror) 
endif (ENABLE_WERROR)

if (CMAKE_GENERATOR STREQUAL "Unix Makefiles")
  set(CMAKE_COLOR_MAKEFILE ON)
endif()

# Enables build with -fcolor-diagnostics if available
if (CMAKE_VERSION VERSION_GREATER_EQUAL "3.24.0")
  set(CMAKE_COLOR_DIAGNOSTICS ON)
endif()

if (ENABLE_ADDRESS_SANITIZER)
    set(ASAN_CXX_FLAGS -fsanitize=address)
    set(ASAN_LINKER_FLAGS -fsanitize=address)
    set(CMAKE_REQUIRED_FLAGS "${ASAN_LINKER_FLAGS}")
    check_cxx_compiler_flag("${ASAN_CXX_FLAGS}" HAVE_ADDRESS_SANITIZER)
    unset(CMAKE_REQUIRED_FLAGS)
    if (HAVE_ADDRESS_SANITIZER)
        add_compile_options(${ASAN_CXX_FLAGS})
        add_link_options(${ASAN_LINKER_FLAGS})
    else ()
        message(SEND_ERROR "Could not enable the address sanitizer!")
    endif ()
endif (ENABLE_ADDRESS_SANITIZER)

if (ENABLE_UB_SANITIZER)
    set(UBSAN_CXX_FLAGS -fsanitize=undefined -fno-sanitize=alignment)
    set(UBSAN_LINKER_FLAGS -fsanitize=undefined -fno-sanitize=alignment)
    set(CMAKE_REQUIRED_FLAGS "${UBSAN_LINKER_FLAGS}")
    check_cxx_compiler_flag("${UBSAN_CXX_FLAGS}" HAVE_UB_SANITIZER)
    unset(CMAKE_REQUIRED_FLAGS)
    if (HAVE_UB_SANITIZER)
        add_compile_options(${UBSAN_CXX_FLAGS})
        add_link_options(${UBSAN_LINKER_FLAGS})
    else ()
        message(SEND_ERROR "Could not enable the undefined behavior sanitizer!")
    endif ()
endif (ENABLE_UB_SANITIZER)

if (ENABLE_THREAD_SANITIZER)
    set(TSAN_CXX_FLAGS -fsanitize=thread)
    set(TSAN_LINKER_FLAGS -fsanitize=thread)
    set(CMAKE_REQUIRED_FLAGS "${TSAN_LINKER_FLAGS}")
    check_cxx_compiler_flag("${TSAN_CXX_FLAGS}" HAVE_THREAD_SANITIZER)
    unset(CMAKE_REQUIRED_FLAGS)
    if (HAVE_THREAD_SANITIZER)
        add_compile_options(${TSAN_CXX_FLAGS})
        add_link_options(${TSAN_LINKER_FLAGS})
    else ()
        message(SEND_ERROR "Could not enable the thread sanitizer!")
    endif ()
endif (ENABLE_THREAD_SANITIZER)
